### PR TITLE
ELF: Fix Sym64.value size

### PR DESCRIPTION
**Pull request by Junraa**

### CODE REVIEW

**Comment by serpilliere** [comment]
Hi! Thanks for the fix!
Remark: it seems the _sym64.value_ is a _u64_. In _elfesteem_, the _ptr_ is mostly used when a structure is shared between 32 and 64 bit versions, and has the size of the _void_.
In this case, the _Sym64_ is always used in 64 bit ELF.

Can you fix it using a _u64_ instead of a _ptr_?

**Comment by Junraa** [comment]
Should do the job. I'll be working with elfesteem for a moment, I'll let you know if I find something else :)

**Comment by serpilliere** [comment]
Thanks!
Just another question: The commit b39d515 appears in the PR now (there are 2 files commited),  while the PR should only display the file containing the modification. Where you on the latest master branch for your second fix?

**Comment by Junraa** [comment]
Yep sorry, it should be fixed now.

**Comment by serpilliere** [comment]
Perfect: Thanks for the fix!!

**Comment by serpilliere** [comment]
Perfect: Thanks for the fix!!

**Pull request merged**
